using _24hplusdotnetcore.Models;
using System.Collections.Generic;

namespace _24hplusdotnetcore.Common.Constants
{
    public static class LeadF88SeedData
    {
        public static IReadOnlyList<DataConfig> Provinces = new DataConfig[]
        {
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "1", Value = "An Giang"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "2", Value = "Bà Rịa - Vũng Tàu"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "3", Value = "Bắc Giang"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "4", Value = "Bạc Liêu"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "5", Value = "Bắc Ninh"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "6", Value = "Bến Tre"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "7", Value = "Bình Dương"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "8", Value = "Bình Phước"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "9", Value = "Bình Thuận"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "10", Value = "Đà Nẵng"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "11", Value = "Đồng Nai"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "12", Value = "Hà Nội"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "13", Value = "Hải Dương"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "14", Value = "Hải Phòng"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "15", Value = "Hưng Yên"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "16", Value = "Kiên Giang"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "17", Value = "Long An"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "18", Value = "Nam Định"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "19", Value = "Nghệ An"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "20", Value = "Ninh Bình"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "21", Value = "Quảng Ninh"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "22", Value = "Sóc Trăng"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "23", Value = "Tây Ninh"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "24", Value = "Thái Bình"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "25", Value = "Thái Nguyên"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "26", Value = "Thanh hóa"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "27", Value = "Thừa Thiên Huế"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "28", Value = "Tiền Giang"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "29", Value = "TP. Hồ Chí Minh"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "30", Value = "Trà Vinh"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "31", Value = "Vĩnh Long"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "32", Value = "Vĩnh Phúc"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "33", Value = "Cà Mau"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "34", Value = "Đồng Tháp"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "35", Value = "Đăk Lăk"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "36", Value = "Cần Thơ"},
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Province, Key = "37", Value = "Lâm Đồng"}
        };
        
        public static IReadOnlyList<DataConfig> SignAddress = new DataConfig[]
        {
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "AGG0160", Value = "447A/23 Trần Hưng Đạo, P. Bình Khánh, TP. Long Xuyên, An Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "AGG0171", Value = "414 Quốc lộ 91, TT. Cái Dầu, H. Châu Phú, An Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "AGG0176", Value = "253 Thủ Khoa Nghĩa, P. Châu Phú, TP. Châu Đốc, An Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "AGG0188", Value = "1762 Trần Hưng Đạo, P. Mỹ Phước, TP. Long Xuyên, An Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "AGG0203", Value = "292 Lê Lợi, P. Châu Phú B, TP. Châu Đốc, An Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BVU0157", Value = "47 Tổ 1, X. Phước Hưng, H. Long Điền, Bà Rịa - Vũng Tàu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BVU0156", Value = "387 Cách Mạng Tháng 8, P. Phước Nguyên, TP. Bà Rịa, Bà Rịa - Vũng Tàu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BVU0191", Value = "507 Nguyễn An Ninh, P. Nguyễn An Ninh, TP. Vũng Tàu, Bà Rịa - Vũng Tàu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BVU0208", Value = "52 Trương Công Định, P. 3, TP. Vũng Tàu, Bà Rịa - Vũng Tàu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BVU0224", Value = "66 Đường 30/4, P. Thắng Nhất, TP. Vũng Tàu, Bà Rịa - Vũng Tàu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BG", Value = "41 Xương Giang, P. Ngô Quyền, TP. Bắc Giang, Bắc Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BGG0169", Value = "222 Lê Lợi, P. Lê Lợi, TP. Bắc Giang, Bắc Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BLU0159", Value = "43 Trần Phú, P. 7, TP. Bạc Liêu, Bạc Liêu" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BN2", Value = "216 Ngô Gia Tự, P. Suối Hoa, TP. Bắc Ninh, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BNH0146", Value = "147 Nguyễn Văn Cừ, P. Võ Cường, TP. Bắc Ninh, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BNH0162", Value = "146 Phố Vũ, P. Đại Phúc, TP. Bắc Ninh, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BNH0182", Value = "Số 1 Khu 1 phố Mới, TT. Phố Mới, H. Quế Võ, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BNH0219", Value = "128 Đường Minh Khai, P. Đông Ngàn, TX. Từ Sơn, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BNH0235", Value = "Ngã tư Đông Côi, TT. Hồ, H. Thuận Thành, Bắc Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BTE0184", Value = "363A Đoàn Hoàng Minh, P. 5, TP. Bến Tre, Bến Tre" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BTE0245", Value = "110A Đại lộ Đồng Khởi, P. Phú Tân, TP. Bến Tre, Bến Tre" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0103", Value = "129 Phú Lợi, P. Phú Lợi, TP. Thủ Dầu Một, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0110", Value = "102 An Bình, P. An Bình, TP. Dĩ An, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0127", Value = "89 Đường N5, P. Thới Hòa, TX. Bến Cát, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0128", Value = "256 Nguyễn An Ninh, P. Dĩ An, TP. Dĩ An, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0140", Value = "61 Nguyễn Văn Tiết, TT. Lái Thiêu, TP. Thuận An, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0179", Value = "190 Cách mạng tháng 8, P. Phú Cường, TP. Thủ Dầu Một, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0181", Value = "22 tháng 12, Khu dân cư Việt Sing, P. An Phú, TP. Thuận An, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0193", Value = "516 Đại lộ Bình Dương, P. Hưng Định, TP. Thuận An, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BDG0227", Value = "Khu phố Khánh Thạnh, P. Tân Phước Khánh, TX. Tân Uyên, Bình Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BPC0144", Value = "242 Nguyễn Huệ, P. Phú Thịnh, TX. Bình Long, Bình Phước" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BPC0151", Value = "957 Phú Riềng Đỏ, P. Tân Bình, TX. Đồng Xoài, Bình Phước" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BTN0189", Value = "63 Nguyễn Hội, P. Phú Tài, TP. Phan Thiết, Bình Thuận" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BTN0195", Value = "459 Trần Hưng Đạo, P. Đức Thắng, TP. Phan Thiết, Bình Thuận" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "BTN0222", Value = "50 Trần Hưng Đạo, P. Phước Hội, TX. Lagi, Bình Thuận" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "CMU0202", Value = "165 Nguyễn Trãi, P. 9, TP. Cà Mau, Cà Mau" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "CTO0223", Value = "61 đường 26/3, P. Châu Văn Liêm, Q. Ô Môn, Cần Thơ" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "CTO0228", Value = "17B Cách mạng tháng 8, P. An Thới, Q. Bình Thủy, Cần Thơ" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNG0199", Value = "537B Núi Thành, P. Hòa Cường Nam, Q. Hải Châu, Đà Nẵng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DLK0221", Value = "1 Hà Huy Tập, P. Tân Lợi, TP. Buôn Ma Thuột, Đăk Lăk" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DLK0229", Value = "5 Nguyễn Văn Cừ, P. Tân Lập, TP. Buôn Ma Thuột, Đăk Lăk" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0112", Value = "415 Đồng Khởi, P. Tân Mai, TP. Biên Hòa, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0129", Value = "943 Phạm Văn Thuận, P. Tân Mai, TP. Biên Hòa, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0145", Value = "533 Phùng Hưng, P. Tam Phước, TP. Biên Hoà, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0152", Value = "84 Lý Thái Tổ, X. Phước Thiền, H. Nhơn Trạch, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0196", Value = "332 Hồng Thập Tự, P. Xuân Trung, TP. Long Khánh, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0210", Value = "18 Trần Văn Xã, P. Trảng Dài, TP. Biên Hòa, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0232", Value = "01/T Phúc Nhạc 2, X. Gia Tân 3, H. Thống Nhất, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0238", Value = "568 Lê Duẩn, TT. Long Thành, H. Long Thành, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DNI0246", Value = "01 đường Quảng Tiến - Bình Minh, X. Quảng Tiến, H. Trảng Bom, Đồng Nai" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DTP0216", Value = "12-14 QL 30, P. Phú Mỹ, TP. Cao Lãnh, Đồng Tháp" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "DTP0226", Value = "96 Cách mạng tháng 8, P. 2, TP. Cao Lãnh, Đồng Tháp" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNTC", Value = "580 Trường Chinh, P. Ngã Tư Sở, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "383TKT", Value = "383 Trần Khát Chân, P. Thanh Nhàn, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "346DL2", Value = "346 Đường Láng, P. Thịnh Quang, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "1148DL", Value = "1148 Đường Láng, P. Láng Thượng, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN701TD", Value = "701 Trương Định, P. Thịnh Liệt, Q. Hoàng Mai, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNHTM", Value = "151 Hồ Tùng Mậu, P. Cầu Diễn, Q. Nam Từ Liêm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN22KH", Value = "22 Khương Hạ, P. Khương Đình, Q. Thanh Xuân, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN92LL", Value = "92 Lê Lợi, P. Nguyễn Trãi, Q. Hà Đông, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN437TT", Value = "437A Tam Trinh, P. Hoàng Văn Thụ, Q. Hoàng Mai, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN01DT", Value = "1 Đại Từ, P. Đại Kim, Q. Hoàng Mai, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN238DLT", Value = "238 Đê La Thành, P. Ô Chợ Dừa, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN747HHT", Value = "747 Hoàng Hoa Thám, P. Vĩnh Phúc, Q. Ba Đình, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN192KN", Value = "192 Kim Ngưu, P. Quỳnh Mai, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN30AD", Value = "30 An Dương, P. Yên Phụ, Q. Tây Hồ, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN82PH", Value = "82 Phùng Hưng, P. Phúc La, Q. Hà Đông, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN246MD", Value = "246 Mỹ Đình, P. Mỹ Đình 2, Q. Nam Từ Liêm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN352BM", Value = "352 Bạch Mai, P. Bạch Mai, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN62HD", Value = "62 Hàng Đậu, P. Đồng Xuân, Q. Hoàn Kiếm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN560QT", Value = "560 Quang Trung, P. La Khê, Q. Hà Đông, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "850DL", Value = "982 Đường Láng, P. Láng Thượng, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN46NCT", Value = "46 Nguyễn Chí Thanh, P. Ngọc Khánh, Q. Ba Đình, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN01DC", Value = "1 Đội Cấn, P. Đội Cấn, Q. Ba Đình, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN100BT", Value = "100 Bà Triệu, P. Nguyễn Du, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN57KT", Value = "57 Khâm Thiên, P. Khâm Thiên, Q. Ba Đình, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN01CTO", Value = "1 Cầu Tó, X. Tả Thanh Oai, H. Thanh Trì, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN2ANKT", Value = "2A Nguyễn Khánh Toàn, P. Quan Hoa, Q. Cầu Giấy, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN624MK", Value = "624 Minh Khai, P. Vĩnh Tuy, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN119NNV", Value = "119 Nguyễn Ngọc Vũ, P. Trung Hòa, Q. Cầu Giấy, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN2ATDH", Value = "2A Trần Duy Hưng, P. Trung Hòa, Q. Cầu Giấy, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN312DC", Value = "383 Đội Cấn, P. Vĩnh Phúc, Q. Ba Đình, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN265GP", Value = "265 Giải Phóng, P. Phương Mai, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN52LTV", Value = "52 Lương Thế Vinh, P. Trung Văn, Q. Nam Từ Liêm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN218DC", Value = "218 Định Công, P. Định Công, Q. Hoàng Mai, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN39HTM", Value = "39 Hồ Tùng Mậu, P. Mai Dịch, Q. Cầu Giấy, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN381CG", Value = "381 Cầu Giấy, P. Dịch Vọng Hậu, Q. Cầu Giấy, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNK11VH", Value = "Kiot 11-12 Chợ Vĩnh Hưng, P. Vĩnh Hưng, Q. Hoàng Mai, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN104NDC", Value = "99 Trương Định, P. Trương Định, Q. Hai Bà Trưng, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN59NGT", Value = "59 Ngô Gia Tự, P. Đức Giang, Q. Long Biên, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN597NT", Value = "597 Nguyễn Trãi, P. Thanh Xuân Nam, Q. Thanh Xuân, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN81N", Value = "81 Nhổn, P. Phương Canh, Q. Nam Từ Liêm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN106TTT", Value = "106 Tôn Thất Tùng, P. Khương Thượng, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HN505NH", Value = "505 Ngọc Hồi, TT. Văn Điển, H. Thanh Trì, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0123", Value = "457 Hà Huy Tập, TT. Yên Viên, H. Gia Lâm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0132", Value = "136 Phùng Khắc Khoan, P. Quang Trung, TX. Sơn Tây, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0134", Value = "112 Phố Ga, TT. Thường Tín, H. Thường Tín, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0135", Value = "1 Cổ Nhuế, P. Cổ Nhuế 2, Q. Bắc Từ Liêm, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0133", Value = "355 Cao Lỗ, X. Uy Nỗ, H. Đông Anh, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNITL01", Value = "530 Đường Láng, P. Láng Hạ, Q. Đống Đa, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HNI0239", Value = "15 Tổ 2, TT. Xuân Mai, H. Chương Mỹ, Hà Nội" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HDG0198", Value = "186B Điện Biên Phủ, P. Phạm Ngũ Lão, TP. Hải Dương, Hải Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HDG0241", Value = "25 Nguyễn Trãi 1, TT. Sao Đỏ, H. Chí Linh, Hải Dương" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HP", Value = "133 Trần Nguyên Hãn, P. Nghĩa Xá, Q. Lê Chân, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HP5502", Value = "116F Lương Khánh Thiện, P. Lương Khánh Thiện, Q. Ngô Quyền, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HPG0161", Value = "416 Ngô Gia Tự, P. Cát Bi, Q. Hải An, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HPG0201", Value = "57 Đường mới, TT. Núi Đèo, H. Thủy Nguyên, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HPG0230", Value = "113 khu phố 1 tháng 5, TT. Vĩnh Bảo, H. Vĩnh Bảo, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HPG0233", Value = "9 Hải Triều, P. Quán Toan, Q. Hồng Bàng, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HPG0234", Value = "75 Minh Đức, TT. Tiên Lãng, H. Tiên Lãng, Hải Phòng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HYN0149", Value = "667 Nguyễn Văn Linh, TT. Bần, H. Mỹ Hào, Hưng Yên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "HYN0148", Value = "81 Tổ 3, TT. Như Quỳnh, H. Văn Lâm, Hưng Yên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "KGG0172", Value = "180 Trần Phú, P. Vĩnh Thanh Vân, TP. Rạch Giá, Kiên Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "KGG0225", Value = "493 Nguyễn Trung Trực, P. Vĩnh Lạc, TP. Rạch Giá, Kiên Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "LDG0237", Value = "84 Thống Nhất, TT. Liên Nghĩa, H. Đức Trọng, Lâm Đồng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "LAN0153", Value = "42C khu phố 3, TT. Đức Hoà, H. Đức Hoà, Long An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "LAN0164", Value = "263 Nguyễn Đình Chiểu, P. 3, TP. Tân An, Long An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "LAN0190", Value = "104 QL50, TT. Cần Giuộc, H. Cần Giuộc, Long An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "LAN0194", Value = "28 Võ Văn Tần, P. 2, TP. Tân An, Long An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NDH0150", Value = "01 Trường Chinh, P. Bà Triệu, TP. Nam Định, Nam Định" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NAN0170", Value = "22 Nguyễn Văn Cừ, P. Trường Thi, TP. Vinh, Nghệ An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NAN0185", Value = "2 Trần Hưng Đạo, P. Cửa Nam, TP. Vinh, Nghệ An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NAN0186", Value = "339 Lê Duẩn, P. Trung Đô, TP. Vinh, Nghệ An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NAN0231", Value = "14 Đường Lê Viết Thuật, P. Hưng Lộc, TP. Vinh, Nghệ An" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NBH0165", Value = "117 Trần Hưng Đạo, P. Đông Thành, TP. Ninh Bình, Ninh Bình" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "NBH0215", Value = "408 Quang Trung, P. Bắc Sơn, TP. Tam Điệp, Ninh Bình" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0163", Value = "18 Trần Hưng Đạo, P. Trần Hưng Đạo, TP. Hạ Long, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0192", Value = "670 Hạ Long, P. Bãi Cháy, TP. Hạ Long, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0206", Value = "81 Vĩnh Thông, P. Mạo Khê, TX. Đông Triều, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0209", Value = "3 Trần Phú, P. Cẩm Tây, TP. Cẩm Phả, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0217", Value = "369 Trần Phú, P. Cẩm Thành, TP. Cẩm Phả, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0218", Value = "1A Phan Bội Châu, P. Quang Trung, TP. Uông Bí, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "QNH0242", Value = "2 Trần Khánh Dư, P. Quảng Yên, TX. Quảng Yên, Quảng Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "STG0175", Value = "137 Ngô Gia Tự, P. 6, TP. Sóc Trăng, Sóc Trăng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "STG0243", Value = "154 Lê Hồng Phong, P. 3, TP. Sóc Trăng, Sóc Trăng" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNH0158", Value = "KP4 Nội Ô B, TT. Gò Dầu, H. Gò Dầu, Tây Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNH0174", Value = "139 Phạm Văn Đồng, P. Long Hoa, TX. Hòa Thành, Tây Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNH0220", Value = "ĐT6 TT Trảng Bàng, TT. Trảng Bàng, H. Trảng Bàng, Tây Ninh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TBH0197", Value = "227 Bồ Xuyên, P. Bồ Xuyên, TP. Thái Bình, Thái Bình" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNN0130", Value = "229B Cách Mạng Tháng 8, P. Cam Giá, TP. Thái Nguyên, Thái Nguyên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNN0131", Value = "377 Hoàng Văn Thụ, P. Đồng Quang, TP. Thái Nguyên, Thái Nguyên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNN0136", Value = "185 Lương Ngọc Quyến, P. Hoàng Văn Thụ, TP. Thái Nguyên, Thái Nguyên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNN0180", Value = "152 Cách Mạng Tháng 8, P. Phan Đình Phùng, TP. Thái Nguyên, Thái Nguyên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TNN0200", Value = "100 Trường Chinh, P. Ba Hàng, TX. Phổ Yên, Thái Nguyên" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THH", Value = "1 Ngô Quyền, P. Điện Biên, TP. Thanh Hóa, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TH5602", Value = "349 Trần Phú, P. Ba Đình, TP. Thanh Hóa, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THA0138", Value = "1 Trần Phú, P. Ba Đình, TX. Bỉm Sơn, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THA0139", Value = "33 Quang Trung, TT. Tĩnh Gia, H. Tĩnh Gia, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THA0187", Value = "342 Nguyễn Trãi, P. Tân Sơn, TP. Thanh Hóa, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THA0214", Value = "429 Đường 10 tháng 6, TT. Quán Lào, H. Yên Định, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "THA0236", Value = "344 Bà Triệu, P. Đông Thọ, TP. Thanh Hóa, Thanh Hóa" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TTH0177", Value = "289 Nguyễn Trãi, P. Tây Lộc, TP. Huế, Thừa Thiên Huế" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TTH0211", Value = "25 Lý Thường Kiệt, P. Phú Nhuận, TP. Huế, Thừa Thiên Huế" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TTH0212", Value = "186 Điện Biên Phủ, P. Trường An, TP. Huế, Thừa Thiên Huế" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TGG0154", Value = "191 Lê Thị Hồng Gấm, P. 4, TP. Mỹ Tho, Tiền Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TGG0155", Value = "71 Trương Định, P. 2, TX. Gò Công, Tiền Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TGG0168", Value = "1/1 Nguyễn Huỳnh Đức, P. 3, TP. Mỹ Tho, Tiền Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TGG0205", Value = "333 Thanh Tâm, P. 1, TX. Cai Lậy, Tiền Giang" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2002", Value = "1168 CMT8, P. 4, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2001", Value = "935B Âu Cơ, P. Tân Sơn Nhì, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2003", Value = "656 Lạc Long Quân, P. 10, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2004", Value = "174 Gò Dầu, P. Tân Quý, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2005", Value = "57 Lê Quang Định, P. 14, Q. Bình Thạnh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2007", Value = "128 Tô Hiến Thành, P. 15, Q. 10, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2008", Value = "23A Phan Đăng Lưu, P. 3, Q. Bình Thạnh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2006", Value = "45B Phan Huy Ích, P. 15, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2009", Value = "237 Lê Văn Thọ, P. 9, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2010", Value = "547 Quang Trung, P. 10, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2011", Value = "349 Lê Văn Sỹ, P. 13, Q. 3, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2012", Value = "1055 Lê Đức Thọ, P. 16, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2013", Value = "394 Nguyễn Sơn, P. Phú Thọ Hòa, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2014", Value = "54H Nguyễn Ảnh Thủ, P. Hiệp Thành, Q. 12, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2016", Value = "605 Hương Lộ 2, P. Bình Trị Đông, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2015", Value = "94 Lê Văn Khương, P. Thới An, Q. 12, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2018", Value = "329 Tô Ngọc Vân, P. Linh Đông, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2017", Value = "39A Tân Hòa Đông, P. 14, Q. 6, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2020", Value = "1 Phùng Tá Chu, P. An Lạc, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2019", Value = "279 Lãnh Binh Thăng, P. 12, Q. 11, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2022", Value = "143 Nguyễn Duy Trinh, P. Bình Trưng Tây, Q. 2, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2021", Value = "B101 Nguyễn Văn Quá, P. Đông Hưng Thuận, Q. 12, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2023", Value = "453 Thống Nhất, P. 16, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2025", Value = "205B Bà Hom, P. 13, Q. 6, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2024", Value = "92 Cao Văn Lầu, P. 2, Q. 6, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2026", Value = "128 Cách Mạng Tháng 8, P. 10, Q. 3, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2027", Value = "121A Nguyễn Xí, P. 26, Q. Bình Thạnh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2028", Value = "158 Lê Văn Việt, P. Tăng Nhơn Phú B, Q. 9, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2029", Value = "1017 Lạc Long Quân, P. 11, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2030", Value = "191 Bình Thới, P. 9, Q. 11, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2032", Value = "13 Nguyên Hồng, P. 1, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2035", Value = "121 Nguyễn Thị Tú, P. Bình Hưng Hòa B, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2036", Value = "324b Phan Đình Phùng, P. 1, Q. Phú Nhuận, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2034", Value = "339 Phạm Thế Hiển, P. 3, Q. 8, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2033", Value = "398 Tô Ký, P. Tân Chánh Hiệp, Q. 12, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2037", Value = "912 Tân Kỳ Tân Quý, P. Bình Hưng Hòa, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2038", Value = "58 Cao Xuân Dục, P. 13, Q. 8, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2039", Value = "115 Tân Kỳ Tân Quý, P. Tân Sơn Nhì, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2041", Value = "7 Lê Hoàng Phái, P. 17, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2042", Value = "128/1 Nguyễn Ảnh Thủ, X. Trung Chánh, H. Hóc Môn, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2040", Value = "74 Hiệp Bình, P. Hiệp Bình Chánh, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2043", Value = "332 Đỗ Xuân Hợp, P. Phước Long A, Q. 9, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2045", Value = "A30/14 Ấp 1 (Quốc lộ 50), X. Bình Hưng, H. Bình Chánh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2044", Value = "1034 Kha Vạn Cân, P. Linh Chiểu, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2047", Value = "393 Nguyễn Thị Thập, P. Tân Phong, Q. 7, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2048", Value = "867 Phan Văn Trị, P. 7, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2052", Value = "125 Hoàng Diệu, P. 12, Q. 4, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2050", Value = "547 Hậu Giang, P. 11, Q. 6, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2051", Value = "683 Lũy Bán Bích, P. Phú Thạnh, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SG2049", Value = "952 Tỉnh lộ 43, P. Bình Chiểu, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0101", Value = "95 Trường Chinh, P. 12, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0102", Value = "730B Hưng Phú, P. 10, Q. 8, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0104", Value = "25/1 Phan Văn Hớn, X. Xuân Thới Thượng, H. Hóc Môn, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0105", Value = "95A Phạm Văn Hai, P. 3, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0106", Value = "644 Nguyễn Duy Trinh, P. Bình Trưng Đông, Q. 2, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0108", Value = "166 Đặng Văn Bi, P. Bình Thọ, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0109", Value = "698 Âu Cơ, P. 14, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0111", Value = "69 Xô Viết Nghệ Tĩnh, P. 17, Q. Bình Thạnh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0113", Value = "43E Hòa Bình, P. Tân Thới Hòa, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0114", Value = "80 Hoàng Diệu 2, P. Linh Chiểu, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0115", Value = "162 Nguyễn Ảnh Thủ, X. Thới Tam Thôn, H. Hóc Môn, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0116", Value = "178P Nơ Trang Long, P. 11, Q. Bình Thạnh, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0117", Value = "150 Lương Nhữ Học, P. 11, Q. 5, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0118", Value = "4/32 Lý Thường Kiệt, TT. Hóc Môn, H. Hóc Môn, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0119", Value = "664 Lê Văn Khương, P. Thới An, Q. 12, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0121", Value = "577 Trần Xuân Soạn, P. Tân Hưng, Q. 7, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0122", Value = "270 Nguyễn Thị Nhỏ, P. 4, Q. 11, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0124", Value = "2A Lũy Bán Bích, P. Tân Thới Hòa, Q. Tân Phú, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0125", Value = "510 Dương Bá Trạc, P. 1, Q. 8, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0126", Value = "48 Trần Nhân Tôn, P. 2, Q. 10, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0141", Value = "1248 tỉnh lộ 10, P. Tân Tạo, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0142", Value = "415 Kha Vạn Cân, P. Linh Đông, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0143", Value = "113 Phạm Văn Chiêu, P. 14, Q. Gò Vấp, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0147", Value = "409C Lý Thường Kiệt, P. 8, Q. Tân Bình, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0166", Value = "307 Bình Long, P. Bình Hưng Hòa A, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0167", Value = "172 Kinh Dương Vương, P. An Lạc, Q. Bình Tân, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0204", Value = "Số 1 đường 11, P. Linh Xuân, Q. Thủ Đức, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "SGN0244", Value = "142B Nguyễn Văn Khạ, TT. Củ Chi, H. Củ Chi, TP. Hồ Chí Minh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "TVH0183", Value = "194 Nguyễn Thị Minh Khai, P. 7, TP. Trà Vinh, Trà Vinh" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "VLG0178", Value = "64/6 Trần Phú, P. 4, TP. Vĩnh Long, Vĩnh Long" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "VY", Value = "31 Mê Linh, P. Liên Bảo, TP. Vĩnh Yên, Vĩnh Phúc" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "VPC0137", Value = "149 Trường Chinh, P. Đồng Xuân, TP. Phúc Yên, Vĩnh Phúc" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "VPC0207", Value = "179 Hùng Vương, P. Hội Hợp, TP. Vĩnh Yên, Vĩnh Phúc" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88SignAddress, Key = "VPC0213", Value = "3 Trần Hưng Đạo, P. Hùng Vương, TP. Phúc Yên, Vĩnh Phúc" },
        };

        public static IReadOnlyList<DataConfig> Categories = new DataConfig[]
        {
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "1", Value = "Đăng ký xe máy" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "2", Value = "Xe máy" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "3", Value = "Đăng ký ô tô" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "4", Value = "Ô tô" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "5", Value = "Điện thoại" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "6", Value = "Laptop" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "7", Value = "Ipad" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "8", Value = "Tablet" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "9", Value = "Trang sức" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "10", Value = "Đồng hồ" },
            new DataConfig{GreenType = GreenType.GreenF, Type = DataConfigType.F88Category, Key = "11", Value = "Khác" },
        };
    }
}
